name = "any"
version = "1.0.0"
license = "license"
author = "Tomohiro Degawa"
maintainer = "degawa.tomohiro@gmail.com"
copyright = "Copyright 2023, Tomohiro Degawa"

[build]
auto-executables = false
auto-tests = true
auto-examples = true

[install]
library = false

[dependencies]
fassert = { git="https://github.com/degawa/fassert" }
